package rollbar

type CrashReportNotification struct {
	baseNotification
	notifierCrashReportBody `json:"body"`
}

// Body container for NotifierCrashReport
type notifierCrashReportBody struct {
	CrashReport NotifierCrashReport `json:"crash_report,omitempty"`
}

type NotifierCrashReport struct {
	// Raw crash report as string (Required)
	// Rollbar expects the format generated by rollbar-ios
	Raw string `json:"raw"`
}
